name: count_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  envied: ^0.5.4+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  supabase_flutter: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
